### ISSUE TITLE
1.21.3 Update

### ISSUE THREAD

**Issue by MinerFixed** [Lauriichan/JustLootIt#28]

**Comment by Lauriichan** [comment]
I am currently working on a bigger update so I won't be able to do publish an update for 1.21.3 until I'm done with that update

**Comment by MinerFixed** [comment]
No problem, any ETA for 1.21.3 support?

**Comment by Lauriichan** [comment]
Please stop closing tickets randomly....

**Comment by Lauriichan** [comment]
If this wouldn't be planned or at least considered then I would close it myself, so please stop randomly closing any issues on any github repository. Usually people use the github issues to keep track of things and you can't look inside their heads and what they think, please don't try to decide on your own what is being done and what not.
I simply can't release an update for 1.21.3 right now because I am working on a bigger update which already has a lot of code modifications that can't be simply undone.

**Comment by Lauriichan** [comment]
Added in a75c7f8e82cd7d606bad4820baf73d509ef2d736
Release will be sometime soonish

**Comment by Lauriichan** [comment]
I don't really get why someone would just delete their messages...

Here the messages: (Ticket description)
![image](https://github.com/user-attachments/assets/1e8a234a-03e3-4dfb-93fc-dc6115768872)

And for the question that I answered:
![image](https://github.com/user-attachments/assets/c5a5a3ef-683d-41e5-a60f-9b47263a2664)
> nope
